### ISSUE TITLE
Customize schema type

### ISSUE THREAD

**Issue by sitch** [annatel/annacl#1]
Hey thanks so much -- just found this repo!

One thing that would be helpful is to allow customizing the echo schema by having:

```elixir
# config.exs
config :annacl,
  schema: MySchema
```

```elixir
defmodule MySchema do
  defmacro __using__(_) do
    quote do
      use Ecto.Schema
      import Ecto.Changeset

      @primary_key {:id, :id, autogenerate: true}
      @foreign_key_type :id
      @timestamps_opts [type: :utc_datetime_usec]

      @type t :: %__MODULE__{}
    end
  end
end
```
As there isn't currently another way other than forking the repo to modify the schemas

**Comment by elielhaouzi** [comment]
Hi @sitch,

Which schema do you want to modify ? your schemas or the schemas of annacl ?

Annacl can be used with all schema, you only need to add a `performer_id` to your schema as shown in [Usage](https://github.com/annatel/annacl#usage)

Can you add your specific needs? i will try to be more useful

**Comment by sitch** [comment]
obviously the schemas in annacl... `binary_id`'s aren't the best choice in pk for more static permission tables as they are bloated and less performant for indexing -- only when you have lots of distributed inserts do they shine, otherwise they just perform worse across the board

**Comment by sitch** [comment]
the example above is just an example of how you could easily modify `https://github.com/annatel/annacl/blob/master/lib/annacl/schema.ex` -- maybe that wasn't clear?

**Comment by elielhaouzi** [comment]
ohhh I get it :)

you're right about binary id that they under perform for indexing compared to integer. but in real, when you don't have a lot of entities (thousands) the difference is minor.

Back to your question, I can add the possibility to configure the base schema, and set it one as a default. according to my current works it will take me one to two weeks to submit that :)

**Comment by elielhaouzi** [comment]
I released a [new tag](https://github.com/annatel/annacl/releases/tag/1.0.0) with the binary_id removed.

I didn't provide an upgrade path, due to a lack of time and I don't think there is a lot of users that are using the lib. 
At this point of the lib, I think it is acceptable.

Enjoy. Any other feedback will be appreciated.
